//renovar o token

//curl -X POST http://localhost:5130/api/auth/login -H "Content-Type: application/json" -d '{
//"email":"admin@orderflow.com",
//"password":"001122"
//}'



//GET http://localhost:5130/api/orders/999999
//GET http://localhost:5130/api/orders
//GET http://localhost:5130/api/orders?page=2&pageSize=5
//GET http://localhost:5130/api/orders?clientId=1
//GET http://localhost:5130/api/orders?description=Sonic
//GET http://localhost:5130/api/orders?page=0&pageSize=10
//GET http://localhost:5130/api/orders?clientId=1&description=Sonic
//GET http://localhost:5130/api/orders?sortBy=description
//GET http://localhost:5130/api/orders?sortBy=description&sortDirection=desc
//GET http://localhost:5130/api/orders?sortBy=clientId


GET http://localhost:5130/api/orders?sortBy=banana
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBvcmRlcmZsb3cuY29tIiwiZXhwIjoxNzgzNjAyMjYwLCJpc3MiOiJPcmRlckZsb3ciLCJhdWQiOiJPcmRlckZsb3dVc2VycyJ9.IFGs01mjXtl22ZicY5OP9DAkZJv1oOBARarFCm0zWTE



### Criar pedido

POST http://localhost:5130/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBvcmRlcmZsb3cuY29tIiwiZXhwIjoxNzgzNTIzODk2LCJpc3MiOiJPcmRlckZsb3ciLCJhdWQiOiJPcmRlckZsb3dVc2VycyJ9.RVWAgL7D4FraAIrxkFzvfKZcUtEFBfMojyHiinAHLvk
Content-Type: application/json

{
    "description": "Sonic Superstars",
    "clientId": 2
}



