//renovar o token

//curl -X POST http://localhost:5130/api/auth/login -H "Content-Type: application/json" -d '{
//"email":"admin@orderflow.com",
//"password":"001122"
//}'



//GET http://localhost:5130/api/orders/999999
//GET http://localhost:5130/api/orders
//GET http://localhost:5130/api/orders?page=2&pageSize=5
//GET http://localhost:5130/api/orders?clientId=1
//GET http://localhost:5130/api/orders?description=Sonic
//GET http://localhost:5130/api/orders?page=0&pageSize=10
//GET http://localhost:5130/api/orders?clientId=1&description=Sonic
//GET http://localhost:5130/api/orders?sortBy=description
//GET http://localhost:5130/api/orders?sortBy=description&sortDirection=desc
//GET http://localhost:5130/api/orders?sortBy=clientId
//GET http://localhost:5130/api/orders?sortBy=banana
//GET http://localhost:5130/api/orders?status=1

// GET /api/orders?minAmount=100
// GET /api/orders?maxAmount=500
// GET /api/orders?minAmount=100&maxAmount=500
// GET /api/orders?status=Pending&minAmount=100
// GET /api/orders?sortBy=amount


GET http://localhost:5130/api/orders?sortBy=amount&sortDirection=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBvcmRlcmZsb3cuY29tIiwiZXhwIjoxNzg0MTk5ODU5LCJpc3MiOiJPcmRlckZsb3ciLCJhdWQiOiJPcmRlckZsb3dVc2VycyJ9.9LODq8IUi_ERa4WQLK0orW1Nb9nh82ULGSeWpeLMaRM



### Criar pedido

POST http://localhost:5130/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBvcmRlcmZsb3cuY29tIiwiZXhwIjoxNzg0MTk5ODU5LCJpc3MiOiJPcmRlckZsb3ciLCJhdWQiOiJPcmRlckZsb3dVc2VycyJ9.9LODq8IUi_ERa4WQLK0orW1Nb9nh82ULGSeWpeLMaRM
Content-Type: application/json

{
    "description": "Sonic Frontiers: Definitive Edition",
    "amount": 350,
    "clientId": 2
}



